import os
import requests
import logging
from time import sleep
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

def get_search_console_data(access_token, gsc_sites):
    rows = []
    page_regex = os.environ["AUTOMATION_PAGE_REGEX"] # only want pages generated by the automation

    for site in gsc_sites:
        encoded_site = site['gsc_property'].replace('://', '%3A%2F%2F').replace('/', '%2F')
        for attempt in range(3):
            try:
                response = requests.post(
                    f'https://www.googleapis.com/webmasters/v3/sites/{encoded_site}/searchAnalytics/query',
                    headers={'Authorization': f'Bearer {access_token}'},
                    json={
                        'startDate': (datetime.now() - timedelta(days=90)).strftime('%Y-%m-%d'),
                        'endDate': datetime.now().strftime('%Y-%m-%d'),
                        'dimensions': ['page'],
                        'dimensionFilterGroups': [{
                            'filters': [{
                                'dimension': 'page',
                                'operator': 'includingRegex',
                                'expression': page_regex
                            }]
                        }],
                        'rowLimit': 25000
                    }
                )
                break
            except Exception:
                if attempt < 2:
                    logger.warning(f"Attempt {attempt + 1} failed. Retrying...")
                    sleep(2)
                else:
                    raise

        response.raise_for_status()
        data = response.json()
        for item in data.get('rows', []):
            row = {
                "site_key": site['key'][:499],
                "site_url": site['site'][:499],
                "page_url": item['keys'][0][:499],
                "clicks": item['clicks'],
                "impressions": item['impressions'],
                "ctr": item['ctr'],
                "position": item['position']
            }
            rows.append(row)

            if len(rows) > 100:
                yield rows
                rows = []

    if rows:
        logger.info(f"Yielding final batch of {len(rows)}")
        yield rows
